FROM node:10

WORKDIR /usr/src/app

#ARG PORT
#ARG HOST
#ARG SERVICE_2_PORT
#ARG SERVICE_2_HOST
#ARG SERVICE_3_PORT
#ARG SERVICE_3_HOST
#
#ENV PORT=$PORT
#ENV HOST=$HOST
#ENV SERVICE_2_PORT=$SERVICE_2_PORT
#ENV SERVICE_2_HOST=$SERVICE_2_HOST
#ENV SERVICE_3_PORT=$SERVICE_3_PORT
#ENV SERVICE_3_HOST=$SERVICE_3_HOST


COPY package*.json ./

RUN npm install

COPY . .

#CMD [ "npm", "start" ]